### ISSUE TITLE
Think how to run selected tests

### ISSUE THREAD

**Issue by Genki-S** [Genki-S/ttnt#1]
It might be great if `ttnt-test` like command runs all tests which is selected.

**Comment by Genki-S** [comment]
Idea note: I think I can create new `Rake::TestTask` with `t.test_files = [TEST_FILES_SELECTED_BY_TTNT]` from within TTNT and delegate running test to `Rake::TestTask`.

**Comment by robin850** [comment]
I'm not sure to understand ; what's the difference with the `rake ttnt:test` command here ? I don't think this task can replace the plain old `rake test` command ; it might still be useful to run all the tests (e.g. before a release or to make sure that nothing is broken).

**Comment by Genki-S** [comment]
Yes, you are right. I'm not going to replace the good old `rake test` command :smile: Sorry for being unclear.

I'm planning to define on-the-go `Rake::TestTask` when `rake ttnt:test` is called, to which I will pass selected tests as `t.test_files`. That way, I can create an instance of `Rake::TestTask` with only selected tests as test targets. That way, TTNT can just focus on selecting tests and can delegate the job of running tests to `Rake::TestTask`, I guess.

**Comment by robin850** [comment]
If you are speaking about [these lines](), you can certainly replace them with:

~~~ruby
ruby "#{@task.ruby_opts_string} #{tests.to_a.join(" ")}"
~~~

given that you have a `@task` instance variable that keeps track of the given testing task (i.e. using composition).

**Comment by Genki-S** [comment]
The link may be wrong, but I got the point. I was thinking that I want to provide users the same experience with running `$ rake test` when running `$ rake ttnt:test:run` (except, of course, run tests are selected), so I was thinking of re-producing `Rake::TestTask`.

But since the internal [run command]](https://github.com/ruby/rake/blob/e644af3/lib/rake/testtask.rb#L102-L105) is not likely to change that often, your solution might be better because it's way simpler. I'll go with your idea at first, thank you so much for sharing this! :smile:

**Comment by robin850** [comment]
Yes, sorry I forgot to add the link to [the lines](https://github.com/Genki-S/ttnt/blob/master/lib/ttnt/testtask.rb#L49-L52)).

> I'll go with your idea at first,

Yep, at least we have something that run the tests even though it's not perfect. :-)

**Comment by Genki-S** [comment]
#18 implemented the run logic :muscle:
