### ISSUE TITLE
Run commit's tests changed or added

### ISSUE THREAD

**Issue by robin850** [Genki-S/ttnt#23]
Hi!

What would be really cool would be to actually run the tests that are changed or added inside the commit. The `TTNT::TestToCodeMapping#get_tests` method will mostlikely never return an associated test file for a test file.

Thus, [this logic](https://github.com/Genki-S/ttnt/blob/master/lib/ttnt/test_selector.rb#L32-L46) (by the way, the `else` is pretty useless here, it could be removed :p) should certainly not be reached when `file` is a test file ; it should be directly added to the tests set.

What do you think ?

**Comment by Genki-S** [comment]
You are right! Thank you for noticing :+1: 

I thought the test file itself is included in the coverage information when running the test, but it seems to be not the case :disappointed: 

I'll fix it right away!

**Comment by Genki-S** [comment]
I forgot to close this; this is implemented in #24
