### ISSUE TITLE
Set `TARGET_SHA` as current working tree by default

### ISSUE THREAD

**Issue by Genki-S** [Genki-S/ttnt#26]
Currently, `TARGET_SHA` is set to `HEAD` by default, which means tests are selected based on anchored commit and HEAD commit by default. However, I noticed I want to run tests when I am writing code, even before I commit it. So, I am planning to make `rake ttnt:test:run` regards changes in current working tree as well.

**Comment by robin850** [comment]
A big :+1: here!

**Comment by robin850** [comment]
This can be closed as #29 has been merged.

**Comment by Genki-S** [comment]
Oh, that's right. Thank you! :smile:
