### ISSUE TITLE
Investigate another approach to monkey-patch Rake's test task

### ISSUE THREAD

**Issue by Genki-S** [Genki-S/ttnt#3]
Idea from Robin.

Call `Coverage.start` at the start of the task and `Coverage.result` (and other stuffs) at the end.

**Comment by robin850** [comment]
Finally, I guess, monkey-patching may not be a good idea. It may still be useful to run the full suite  without this feature.

Creating rake tasks for each purpose may be better. Something like `rake test:coverage` to create/update the coverage file and a rake task to run the tests given a commit (defaults to `HEAD`). I'm not sure about the name though (`test:pick SHA`, `test:select SHA` or just `test:commit SHA`).

What do you think ?

**Comment by Genki-S** [comment]
> Creating rake tasks for each purpose may be better

Agreed :smile: Actually I didn't know it's possible :sweat: I will try that way!

And yes, naming is the biggest problem for me for weeks.
I'm feeling generating coverage file is like anchoring, so `rake test:anchor` is my current choice. But I'm not sure if the name represents what the task actually does :disappointed: 
For running selected tests, I have no good idea in the form `rake test:SOMETHING`... maybe `rake test:selective_run`? seems a little too verbose, though...

Using the gem name as task namespace might be an option (though it requires users to learn the concept of this gem). I temporarily named this gem as `ttnt` (acronym for "Test This, Not That!") so task names might be `rake ttnt:coverage` or `rake ttnt:anchor` (which produces coverage file) and `rake ttnt:{pick,select,commit}` or `rake ttnt:run`  (which runs selected tests).

In my opinion, at first it's better not to pollute `test:` namespace because this gem is too young to reside in there. But in the future I hope that running only tests related to changes in code is so popular that these tasks naturally reside under `test:` namespace (or even entirely replace the `rake test` behavior!).

**Comment by robin850** [comment]
Don't care too much about naming. :-) Namespacing under `ttnt` seems fine but we can rename things or create aliases later anyway.  :+1:

**Comment by Genki-S** [comment]
That's true, I will stick to `ttnt` namespace for now, then :smile:

**Comment by Genki-S** [comment]
Rake tasks are introduced in #6 , so I'm closing this.
