### ISSUE TITLE
What information, and how it should be stored as test-to-code mapping?

### ISSUE THREAD

**Issue by Genki-S** [Genki-S/ttnt#5]
related: #4

In order to optimize file size and performance, we need some strategies.

Current direction:

- test-to-code mapping is stored as single file
- test-to-code mapping is version controlled

**Comment by robin850** [comment]
This is closely related to #3 but what would be cool would be to provide options along the lines of `Rake::TestTask` to customize which test files and which code files should be covered. Something like:

~~~~ruby
Rake::TtntTask do |t|
  t.test_files = "test/**/*_test.rb"
  t.code_files = "{actionpack,actionview}/**/*.rb"
end
~~~

Thus we can reduce the number of information stored inside the coverage file easily. What do you think ?

**Comment by Genki-S** [comment]
This is really cool! This will make TTNT satisfy various use cases :+1: I will definitely implement this feature. Thank you for your great idea, I'm so excited! :smile: 

My first shot (implemented in [this branch](https://github.com/Genki-S/ttnt/tree/rake_tasks_for_ttnt)) is to define Rake tasks by using the instance of `Rake::TestTask` so that the installation can be super easy. The code users write in their `Rakefile` would look like this:

```
require 'rake/testtask'
require 'ttnt/tasks'

Rake::TestTask.new { |t|
  t.libs << "test"
  t.pattern = 'test/**/*_test.rb'
  TTNT::TestTask.new(t)
}
```

(the lines `require 'ttnt/tasks'` and `TTNT::TestTask.new(t)` are the only required ones for TTNT)

I think both approach can co-exist (as an easy-installation method and a customizable one). Could you tell me what do you think of my approach?

**Comment by Genki-S** [comment]
This is implemented in above PRs. Sorry for leaving it open :bow:
